### ISSUE TITLE
[BUG] Sqlalchemy is pinned to 1 - v2 is now out so cant use both packages

### ISSUE THREAD

**Issue by commentator8** [yuval9313/FastApi-RESTful#172]
I am using fastapi-utils, however it is sadly not maintained. I would like to upgrade to sqlalchemy 2 (and don't use the sqlalchemy parts of fastapi-utils) but poetry prevents it due to it being defined here as "^1". Could you please loosen the requirements to ">=1" so that it is possible to use both?

At first glance the sqlalchemy code here is high enough level that it might work out of the box with 2, but i'm interested in InferringRouter and other such more.

Thanks!

**Comment by yuval9313** [comment]
I think you are right, I had worked on "unpinned" version but I have some issues with the tests.

I'll check it up in the next days

**Comment by Zer0x00** [comment]
Are there any updates on this?

**Comment by ollz272** [comment]
@yuval9313 please can this be prioritised?

**Comment by ollz272** [comment]
@yuval9313 i've updated the package to support this

**Comment by yuval9313** [comment]
[Done v0.5.0](https://github.com/yuval9313/FastApi-RESTful/releases/tag/v0.5.0)
