### ISSUE TITLE
[QUESTION] How to add description to Resource endpoint?

### ISSUE THREAD

**Issue by starkgate** [yuval9313/FastApi-RESTful#178]
**Description**

How can I add a description to a Resource's endpoint? I went through the documentation but only saw an explanation on how to describe the response of the endpoint, not the endpoint itself.

For example in the screenshot below, how can I change "Put" to another title, and add a description to the endpoint?
![image](https://user-images.githubusercontent.com/12874678/234210323-983f2e0d-fc6d-4230-89d4-140ad21a4e98.png)

**Comment by yuval9313** [comment]
You can describe the request the same as you would in Fastapi [see this](https://github.com/yuval9313/FastApi-RESTful/issues/89)
