### ISSUE TITLE
[FEATURE] Fastapi-restful (0.4.4) depends on Fastapi 0.96.0 ?

### ISSUE THREAD

**Issue by integrajerome** [yuval9313/FastApi-RESTful#185]
![Capture d'écran 2023-06-08 121807](https://github.com/yuval9313/FastApi-RESTful/assets/91475647/ec1af9af-265f-43aa-9e43-e3578c77b408)

**Comment by ibot3** [comment]
No, it depends on fastapi 0.89.x, which isn't very nice either.

**Comment by jackburns** [comment]
This is impacting version 0.4.3 as well. It looks like a new distribution was pushed yesterday which also includes this breaking change. 

Had to downgrade to 0.4.2 to fix

https://pypi.org/project/fastapi-restful/0.4.3/#files

![image](https://github.com/yuval9313/FastApi-RESTful/assets/5840937/6e29d326-2e9c-4387-bb3e-a7e7fc78bf4e)

![image](https://github.com/yuval9313/FastApi-RESTful/assets/5840937/3f8dcaa0-c3e2-4406-aec9-66ef06af1b28)

**Comment by integrajerome** [comment]
> No, it depends on fastapi 0.89.x, which isn't very nice either.

I confirm it does not at the moment; therefore it is a feature with a question mark. Will it break some funcs in fastapi-restful?

**Comment by yuval9313** [comment]
I think I know what happened, will upload a fix soon enough

**Comment by yuval9313** [comment]
Should be ok with release 0.4.5
