### ISSUE TITLE
Please support pydantic V2

### ISSUE THREAD

**Issue by ollz272** [yuval9313/FastApi-RESTful#198]
**Is your feature request related to a problem? Please describe.**
I want pydantic v2 to be supported so we can use it in fastapi v0.100

**Comment by ollz272** [comment]
PR here https://github.com/yuval9313/FastApi-RESTful/pull/199

**Comment by ollz272** [comment]
@yuval9313 please can you take a look at this

**Comment by ollz272** [comment]
@yuval9313 Work is now done for this - can you make a release when you have a moment? 🙏🏻

**Comment by yuval9313** [comment]
[Done v0.5.0](https://github.com/yuval9313/FastApi-RESTful/releases/tag/v0.5.0) and thanks @ollz272 🥳
