### ISSUE TITLE
Newest release not available on PyPi

### ISSUE THREAD

**Issue by pavelzw** [yuval9313/FastApi-RESTful#213]
![image](https://github.com/yuval9313/FastApi-RESTful/assets/29506042/c0717c59-9162-4302-ad09-65001a8415b2)
![image](https://github.com/yuval9313/FastApi-RESTful/assets/29506042/3e43be04-f740-47fb-b5a7-f2a6d47cd82f)

It would be nice to get 0.5.0 on PyPi.

Edit: just saw #212

**Comment by yuval9313** [comment]
You are correct and I had enough with poetry, and I think I'd switch to hatch/fleet since I don't think poetry is quite right for packaging and it seems like hatch manages it plenty (with fastapi being my inspiration)

**Comment by pavelzw** [comment]
Thanks, it's available now :)

You may want to look at the failing publish CI, though
![image](https://github.com/yuval9313/FastApi-RESTful/assets/29506042/69ab169e-4ab2-4dc6-b680-d15890d4b695)
