### ISSUE TITLE
[QUESTION]How to operate Swagger？

### ISSUE THREAD

**Issue by MgArcher** [yuval9313/FastApi-RESTful#89]
![image](https://user-images.githubusercontent.com/37403293/135242570-1b9ca7b9-f751-44dd-b557-5d0d6581f9cf.png)
How do I write comments in Swegger?

**Comment by yuval9313** [comment]
I think we can do as follows:  
Have the docstring of function to become it's description with `:summary` as summary

**Comment by DanielEidlin** [comment]
As @negadive suggested you can use the `summary` and `description` fields to add information to your API's swagger.
Here is an example using the `@cbv` decorator:

`
@cbv(router)
class ItemsApi:

    @router.post("/item", response_model=Item, summary="Create an item")
    async def post(self, item: Item):
        """
        Create an item with all the information:

        - **name**: each item must have a name
        - **description**: a long description
        - **price**: required
        - **tax**: if the item doesn't have tax, you can omit this
        - **tags**: a set of unique tag strings for this item
        """
        return item
`

![Opera Snapshot_2022-01-11_222527_localhost](https://user-images.githubusercontent.com/33933623/149017833-e0c8b586-42bc-42b6-ad7c-b9876b174e17.png)

**Comment by yuval9313** [comment]
Amazing, thanks @DanielEidlin

**Comment by MgArcher** [comment]
I have an idea for a solution.Modify the cbv_base.py
```cbv_base.py
class Api:
    def __init__(self, app: FastAPI):
        self.app = app

    def add_resource(self, resource: Resource, *urls: str, **kwargs: Any) -> None:
        router = APIRouter()
        _cbv(router, type(resource), *urls, instance=resource)
        self.app.include_router(router)
```

```
from fastapi_restful import Api as api

class Api(api):
    """add_resource"""
    def add_resource(self, resource: Resource, *urls: str, **kwargs: Any) -> None:
        router = APIRouter()
        _cbv(router, type(resource), *urls, instance=resource)
        # alter
        router.routes[0].tags = kwargs.get("tages")
        router.routes[0].summary = kwargs.get("summary")

        self.app.include_router(router)
```
```
api.add_resource(idCard.IdCard(), '/idcard_recoginize', tages=["test"], summary="test2")
```

![8f96728297077b771925fe0146cf861](https://user-images.githubusercontent.com/37403293/149716513-e5d6879e-e913-4ea4-8ca8-cb953dc3ffba.png)

**Comment by yuval9313** [comment]
@DanielEidlin can you review this please?

**Comment by yuval9313** [comment]
Hey, what about the current way to create tags and summaries? it is already supported and works fine
